---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: final-project-cluster
  region: "us-east-1"
  version: "1.31"

availabilityZones: ["us-east-1a" ,"us-east-1b"]
iam:
  serviceRoleARN: arn:aws:iam::396561719560:role/LabRole

managedNodeGroups:
- name: standard-workers
  desiredCapacity: 2
  instanceType: t3.medium
  ssh:
    enableSsm: true
  iam:
    instanceRoleARN: arn:aws:iam::396561719560:role/LabRole
